<?php

/**
 * @file
 * Module hooks and functions for the Google Search Collections module.
 */


/**
 * Implements hook_permission().
 */
function google_search_collections_permission() {
  return array(
    'administer google search collections' => array(
      'title' => t('Administer google search collections'),
      'description' => t('Add, update, and export search collection configs.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function google_search_collections_menu() {
  $prefix = 'search';
  $items = array();

  drupal_static_reset('search_get_info');
  $default_info = search_get_default_module_info();
  foreach (google_search_collections_get_definitions() as $path => $definition) {
    // Ignore disabled collections.
    if (isset($definition->disabled) && $definition->disabled) {
      continue;
    }

    $items[$prefix . '/' . $path] = array(
      'title' => $definition->title,
      'page callback' => 'google_search_collections_search',
      'page arguments' => array($path, ''),
      //'access callback' => '_search_menu_access',
      //'access arguments' => array($module),
      'access callback' => TRUE,
      'type' => MENU_LOCAL_TASK,
      'weight' => isset($definition->data['weight']) ? $definition->data['weight'] : 0,
    );

    $items[$prefix . '/' . $path . '/%menu_tail'] = array(
      'title' => $definition->title,
      'load arguments' => array('%map', '%index'),
      'page callback' => 'google_search_collections_search',
      'page arguments' => array($path, 2),
      //'access callback' => '_search_menu_access',
      //'access arguments' => array($module),
      'access callback' => TRUE,
      'type' => MENU_LOCAL_TASK,
      'weight' => isset($definition->data['weight']) ? $definition->data['weight'] : 0,
      'tab_root' => $prefix . '/' . $default_info['path'] . '/%',
      'tab_parent' => $prefix . '/' . $default_info['path'],
    );
  }

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function google_search_collections_menu_alter(&$menu) {
  // Remove the default GSS search local task in favor of our collections.
  unset($menu['search/gss'], $menu['search/gss/%menu_tail']);
}

/**
 * Page callback, wraps GSA or GSS search page views for maximum control.
 *
 * @param string $collection
 *   The Google Search collection for which the current search is taking place.
 *
 * @param string $keys
 *   The search query.
 *
 * @return
 *   Themed search results for the given collection and keys.
 */
function google_search_collections_search($collection, $keys = '') {
  $definition = google_search_collections_get_definition($collection);

  if ($definition->data['module'] === 'gss') {
    require_once(drupal_get_path('module', 'search') . '/search.pages.inc');
    $callback = 'search_view';
    $arguments = array('gss', $keys);
  }
  elseif ($definition['module'] === 'google_appliance') {
    //
  }
  else {
    $callback = FALSE;
  }

  return $callback ? call_user_func_array($callback, $arguments) : FALSE;
}

/**
 * Implements hook_form_alter().
 */
function google_search_collections_form_alter(&$form, &$form_state, $form_id) {
  $collection = google_search_collections_get_active_collection();
  switch ($form_id) {
    // The GSS module uses core search, perform clean-up here.
    case 'search_form':
    case 'search_block_form':
    case 'search_theme_form':
      $form['#submit'][] = 'google_search_collections_gss_submit';
      $form['#action'] = str_replace('/gss', '/' . $collection, $form['#action']);
      break;
  }
}

/**
 * Implements hook_gss_search_key_alter().
 */
function google_search_collections_gss_search_key_alter(&$key) {
  // Apply query terms.
  $collection = google_search_collections_get_active_collection();
  $definition = google_search_collections_get_definition($collection);

  if (isset($definition->data['queryterms']) && !empty($definition->data['queryterms'])) {
    $key .= ' ' . check_plain($definition->data['queryterms']);
  }
}

/**
 * Implements hook_preprocess_gss_result().
 *
 * Ensures that "inurl" and other pseudo parameters are not included in user-
 * facing search text.
 */
function google_search_collections_preprocess_gss_result(&$variables) {
  $result = $variables['result'];
  if (empty($result['link']) && empty($result['title'])) {
    $default_no_results = variable_get('gss_no_results', array(
      'value' => t('No results'),
      'format' => NULL,
    ));
    $empty_results = format_string($default_no_results['value'], array(
      '@query' => arg(2),
    ));
    $variables['snippet'] = check_markup($empty_results, $default_no_results['format']);
  }
}

/**
 * Submit handler for the GSS search form.
 */
function google_search_collections_gss_submit($form, &$form_state) {
  if (!$collection = google_search_collections_get_active_collection()) {
    $collection = google_search_collections_get_default_collection();
  }

  if (is_array($form_state['redirect'])) {
    $redirect_to = &$form_state['redirect'][0];
  }
  else {
    $redirect_to = &$form_state['redirect'];
  }
  $redirect_to = str_replace('/gss', '/' . $collection, $redirect_to);
}

/**
 * Returns the current, active Google Search collection.
 *
 * @return string|bool
 *   The current active search collection, or false if no collection could be
 *   found.
 */
function google_search_collections_get_active_collection() {
  $args = arg();
  if (count($args) >= 2 && $args[0] === 'search') {
    return $args[1];
  }
  else {
    return FALSE;
  }
}

/**
 * Returns the default Google Search collection.
 */
function google_search_collections_get_default_collection() {
  $collections = google_search_collections_get_definitions();

  // Attempt to find the default.
  foreach ($collections as $collection => $definition) {
    if (isset($definition['default']) && $definition['default']) {
      return $collection;
    }
  }

  // If no default is set, return the first one.
  reset($collections);
  return key($collections);
}

/**
 * Returns a single collection definition.
 *
 * @param string $collection
 *   The desired Google Search collection.
 *
 * @return array|bool
 *   Returns the collection definition if one is found, FALSE otherwise.
 */
function google_search_collections_get_definition($collection) {
  $definitions = google_search_collections_get_definitions();
  return isset($definitions[$collection]) ? $definitions[$collection] : FALSE;
}

/**
 * Helper function that returns all currently known search collection configs.
 */
function google_search_collections_get_definitions($reset = FALSE) {
  ctools_include('export');
  $definitions = drupal_static(__FUNCTION__, array());

  if ($definitions === array() || $reset) {
    ctools_export_load_object_reset('google_search_collections');
    $definitions = ctools_export_load_object('google_search_collections', 'all');
  }

  return $definitions;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function google_search_collections_ctools_plugin_directory($module, $type) {
  // Load the export_ui plugin.
  if ($type === 'export_ui') {
    return 'plugins/export_ui';
  }
}

/**
 * Export callback for Google search collection exportables.
 */
function google_search_collections_export($context, $indent = '') {
  $output = ctools_export_object('google_search_collections', $context, $indent);
  $translatables = array();
  foreach (array('title') as $key) {
    if (!empty($context->{$key})) {
      $translatables[] = $context->{$key};
    }
  }
  $translatables = array_filter(array_unique($translatables));
  if (!empty($translatables)) {
    $output .= "\n";
    $output .= "{$indent}// Translatables included for use with string extractors like potx.\n";
    sort($translatables);
    foreach ($translatables as $string) {
      $output .= "{$indent}t(" . ctools_var_export($string) . ");\n";
    }
  }
  return $output;
}

/**
 * Save callback for Google search collection exportables.
 */
function google_search_collections_save($object) {
  if ($object->export_type & EXPORT_IN_DATABASE) {
    // Existing record.
    $update = array('pid');
  }
  else {
    // New record.
    $update = array();
    $object->export_type = EXPORT_IN_DATABASE;
  }
  $return = drupal_write_record('google_search_collections', $object, $update);

  // Always rebuild the menu when saving a search collection.
  variable_set('menu_rebuild_needed', TRUE);

  return $return;
}

/**
 * Status set callback for Google search collection exportables.
 */
function google_search_collections_set_status($object, $status) {
  ctools_export_set_object_status($object, $status);

  // Always rebuild the menu when updating the status of a search collection.
  variable_set('menu_rebuild_needed', TRUE);
}

/**
 * Delete callback for Google search collection exportables.
 */
function google_search_collections_delete($object) {
  // If we were sent an object, get the export key from it. Otherwise
  // assume we were sent the export key.
  $value = is_object($object) ? $object->pid : $object;
  db_delete('google_search_collections')
    ->condition('pid', $value)
    ->execute();

  // Always rebuild the menu when deleting a search collection.
  variable_set('menu_rebuild_needed', TRUE);
}
